import ReviewImage from "../../../../assets/homepage_imgs/Review-images/review-img.svg";

export const reviews = [
  {
    key: 1,
    name: "Bruce Wayne",
    username: "@brucewayne",
    msg: "Note-taking is the bridge between hearing and understanding, between seeing and remembering.",
    image: { ReviewImage },
  },
  {
    key: 2,
    name: "Bruce Wayne",
    username: "@brucewayne",
    msg: "Note-taking is the bridge between hearing and understanding, between seeing and remembering.",
    image: { ReviewImage },
  },
  {
    key: 3,
    name: "Bruce Wayne",
    username: "@brucewayne",
    msg: "Note-taking is the bridge between hearing and understanding, between seeing and remembering.",
    image: { ReviewImage },
  },
  {
    key: 4,
    name: "Bruce Wayne",
    username: "@brucewayne",
    msg: "Note-taking is the bridge between hearing and understanding, between seeing and remembering.",
    image: { ReviewImage },
  },
  {
    key: 5,
    name: "Bruce Wayne",
    username: "@brucewayne",
    msg: "Note-taking is the bridge between hearing and understanding, between seeing and remembering.",
    image: { ReviewImage },
  },
  {
    key: 6,
    name: "Bruce Wayne",
    username: "@brucewayne",
    msg: "Note-taking is the bridge between hearing and understanding, between seeing and remembering.",
    image: { ReviewImage },
  },
  {
    key: 7,
    name: "Bruce Wayne",
    username: "@brucewayne",
    msg: "Note-taking is the bridge between hearing and understanding, between seeing and remembering.",
    image: { ReviewImage },
  },
  {
    key: 8,
    name: "Bruce Wayne",
    username: "@brucewayne",
    msg: "Note-taking is the bridge between hearing and understanding, between seeing and remembering.",
    image: { ReviewImage },
  },
  {
    key: 9,
    name: "Bruce Wayne",
    username: "@brucewayne",
    msg: "Note-taking is the bridge between hearing and understanding, between seeing and remembering.",
    image: { ReviewImage },
  },
  {
    key: 10,
    name: "Bruce Wayne",
    username: "@brucewayne",
    msg: "Note-taking is the bridge between hearing and understanding, between seeing and remembering.",
    image: { ReviewImage },
  },
  {
    key: 11,
    name: "Bruce Wayne",
    username: "@brucewayne",
    msg: "Note-taking is the bridge between hearing and understanding, between seeing and remembering.",
    image: { ReviewImage },
  },
  {
    key: 12,
    name: "Bruce Wayne",
    username: "@brucewayne",
    msg: "Note-taking is the bridge between hearing and understanding, between seeing and remembering.",
    image: { ReviewImage },
  },
];
