export const course_name = [
  {
    id: 1,
    img: "",
    c_name: "Artificial Intelligence",
    cap: "HarvardX: CS50's Introduction to Artificial Intelligence with Python",
    c_dest: "edX",
    cap_color: "rgba(231, 136, 149, 1)",
    link: "https://www.edx.org/learn/artificial-intelligence/harvard-university-cs50-s-introduction-to-artificial-intelligence-with-python",
  },
  {
    id: 2,
    img: "",
    c_name: "Biology",
    cap: "Introduction to Biology",
    c_dest: "Coursera",
    cap_color: "rgba(161, 151, 252, 1)",
    link: "https://www.coursera.org/specializations/introduction-to-biology",
  },
  {
    id: 3,
    img: "",
    c_name: "Physics",
    cap: "Class 12th Physics",
    c_dest: "BYJU'S",
    cap_color: "rgba(252, 191, 73, 1)",
    link: "https://byjus.com/physics/class-12-physics-index/",
  },

  {
    id: 4,
    img: "",
    c_name: "Machine Learning",
    cap: "Machine Learning",
    c_dest: "Coursera",
    cap_color: "rgba(252, 191, 73, 1)",
    link: "https://www.coursera.org/specializations/machine-learning",
  },
  {
    id: 5,
    img: "",
    c_name: "Computer Science",
    cap: "DSA (Data Structures and Algorithms)",
    c_dest: "GeeksforGeeks",
    cap_color: "rgba(231, 136, 149, 1)",
    link: "https://www.geeksforgeeks.org/data-structures/",
  },
  {
    id: 6,
    img: "",
    c_name: "Java",
    cap: "Java Tutorial",
    c_dest: "Tutorialspoint",
    cap_color: "rgba(161, 151, 252, 1)",
    link: "https://www.tutorialspoint.com/java/index.htm",
  },
  {
    id: 7,
    img: "",
    c_name: "Chemistry",
    cap: "Chemistry 101 - Part 1 Principles of Chemistry",
    c_dest: "Udemy",
    cap_color: "rgba(99, 180, 184, 1)",
    link: "https://www.udemy.com/course/chemistry-101-part-1-principles-of-chemistry/",
  },
  {
    id: 8,
    img: "",
    c_name: "Mathematics",
    cap: "Algebra Basics",
    c_dest: "Khan Academy",
    cap_color: "rgba(99, 180, 184, 1)",
    link: "https://www.khanacademy.org/math/algebra",
  },
  {
    id: 9,
    img: "",
    c_name: "Cyber Security",
    cap: "Introduction to Cyber Security",
    c_dest: "FutureLearn",
    cap_color: "rgba(231, 136, 149, 1)",
    link: "https://www.futurelearn.com/courses/introduction-to-cyber-security",
  },
  {
    id: 10,
    img: "",
    c_name: "Python",
    cap: "Python Tutorial for Beginners",
    c_dest: "YouTube",
    cap_color: "rgba(161, 151, 252, 1)",
    link: "https://www.youtube.com/watch?v=eWRfhZUzrAc",
  },
  {
    id: 11,
    c_name: "Chemistry",
    cap: "General Organic Chemistry",
    c_dest: "Unacademy",
    cap_color: "rgba(99, 180, 184, 1)",
    link: "https://unacademy.com/lesson/course-overview-in-hindi/6K9DFVZO",
  },
  {
    id: 12,
    img: "",
    c_name: "Web Development",
    cap: "The Complete Web Development Bootcamp",
    c_dest: "Udemy",
    cap_color: "rgba(252, 191, 73, 1)",
    link: "https://www.udemy.com/course/the-complete-web-development-bootcamp/",
  },
];
