import AI from "../../assets/Images/CourseSlider2/AI.svg";
import Bio from "../../assets/Images/CourseSlider2/BioSlide.svg";
import Phy from "../../assets/Images/CourseSlider2/PhySlide.svg";
import Chem from "../../assets/Images/CourseSlider2/ChemSlide.svg";

export const course_name = [
  {
    id: 1,
    img: AI,
    c_name: "1",
    cap: "Adv AI course",
    c_dest: "Udemy",
    cap_color: "rgba(231, 136, 149, 1)",
  },
  {
    id: 2,
    img: Bio,
    c_name: "2",
    cap: "Adv AI course",
    c_dest: "Udemy",
    cap_color: "rgba(161, 151, 252, 1)",
  },
  {
    id: 3,
    img: Phy,
    c_name: "3",
    cap: "Adv AI course",
    c_dest: "Udemy",
    cap_color: "rgba(99, 180, 184, 1)",
  },
  {
    id: 4,
    img: Chem,
    c_name: "4",
    cap: "Adv AI course",
    c_dest: "Udemy",
    cap_color: "rgba(252, 191, 73, 1)",
  },
  {
    id: 5,
    img: AI,
    c_name: "5",
    cap: "Adv AI course",
    c_dest: "Udemy",
    cap_color: "rgba(231, 136, 149, 1)",
  },
  {
    id: 6,
    img: Bio,
    c_name: "6",
    cap: "Adv AI course",
    c_dest: "Udemy",
    cap_color: "rgba(161, 151, 252, 1)",
  },
  {
    id: 7,
    img: Phy,
    c_name: "7",
    cap: "Adv AI course",
    c_dest: "Udemy",
    cap_color: "rgba(99, 180, 184, 1)",
  },
  {
    id: 8,
    img: Chem,
    c_name: "8",
    cap: "Adv AI course",
    c_dest: "Udemy",
    cap_color: "rgba(252, 191, 73, 1)",
  },
  {
    id: 9,
    img: AI,
    c_name: "9",
    cap: "Adv AI course",
    c_dest: "Udemy",
    cap_color: "rgba(231, 136, 149, 1)",
  },
  {
    id: 10,
    img: Bio,
    c_name: "10",
    cap: "Adv AI course",
    c_dest: "Udemy",
    cap_color: "rgba(161, 151, 252, 1)",
  },
  {
    id: 11,
    img: Phy,
    c_name: "11",
    cap: "Adv AI course",
    c_dest: "Udemy",
    cap_color: "rgba(99, 180, 184, 1)",
  },
  {
    id: 12,
    img: Chem,
    c_name: "12",
    cap: "Adv AI course",
    c_dest: "Udemy",
    cap_color: "rgba(252, 191, 73, 1)",
  },
];
