export const cards = [
  {
    id: 1,
    date: "08.04.24",
    noteName: "Biology Notes",
    desc: "Wormhole invites creatives to craft an engaging and informative explainer video aimed at beginners interested in understanding what Wormhole is and its significance in the web3 ecosystem.",
    time: "10.13 PM, Sunday",
    color: " rgba(129, 194, 198, 1)",
  },
  {
    id: 2,
    date: "08.04.24",
    noteName: "Physics Notes",
    desc: "Wormhole invites creatives to craft an engaging and informative explainer video aimed at beginners interested in understanding what Wormhole is and its significance in the web3 ecosystem.",
    time: "10.13 PM, Sunday",
    color: "rgba(96, 198, 220, 1)",
  },
  {
    id: 3,
    date: "08.04.24",
    noteName: "Chemistry Notes",
    desc: "Wormhole invites creatives to craft an engaging and informative explainer video aimed at beginners interested in understanding what Wormhole is and its significance in the web3 ecosystem.",
    time: "10.13 PM, Sunday",
    color: "rgba(252, 203, 109, 1)",
  },
  {
    id: 4,
    date: "08.04.24",
    noteName: "Mathematics Notes",
    desc: "Wormhole invites creatives to craft an engaging and informative explainer video aimed at beginners interested in understanding what Wormhole is and its significance in the web3 ecosystem.",
    time: "10.13 PM, Sunday",
    color: "rgba(179, 171, 252, 1)",
  },
  {
    id: 5,
    date: "08.04.24",
    noteName: "Biology Notes",
    desc: "Wormhole invites creatives to craft an engaging and informative explainer video aimed at beginners interested in understanding what Wormhole is and its significance in the web3 ecosystem.",
    time: "10.13 PM, Sunday",
    color: " rgba(129, 194, 198, 1)",
  },
  {
    id: 6,
    date: "08.04.24",
    noteName: "Physics Notes",
    desc: "Wormhole invites creatives to craft an engaging and informative explainer video aimed at beginners interested in understanding what Wormhole is and its significance in the web3 ecosystem.",
    time: "10.13 PM, Sunday",
    color: "rgba(96, 198, 220, 1)",
  },
  {
    id: 7,
    date: "08.04.24",
    noteName: "Chemistry Notes",
    desc: "Wormhole invites creatives to craft an engaging and informative explainer video aimed at beginners interested in understanding what Wormhole is and its significance in the web3 ecosystem.",
    time: "10.13 PM, Sunday",
    color: "rgba(252, 203, 109, 1)",
  },
  {
    id: 8,
    date: "08.04.24",
    noteName: "Mathematics Notes",
    desc: "Wormhole invites creatives to craft an engaging and informative explainer video aimed at beginners interested in understanding what Wormhole is and its significance in the web3 ecosystem.",
    time: "10.13 PM, Sunday",
    color: "rgba(179, 171, 252, 1)",
  },
  {
    id: 9,
    date: "08.04.24",
    noteName: "Biology Notes",
    desc: "Wormhole invites creatives to craft an engaging and informative explainer video aimed at beginners interested in understanding what Wormhole is and its significance in the web3 ecosystem.",
    time: "10.13 PM, Sunday",
    color: " rgba(129, 194, 198, 1)",
  },
  {
    id: 10,
    date: "08.04.24",
    noteName: "Physics Notes",
    desc: "Wormhole invites creatives to craft an engaging and informative explainer video aimed at beginners interested in understanding what Wormhole is and its significance in the web3 ecosystem.",
    time: "10.13 PM, Sunday",
    color: "rgba(96, 198, 220, 1)",
  },
];
